#!/bin/bash
#
# sesoonide määramine
#
echo -n "sisesta kuu number: "
read kuu
#
if [ $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12 ]; then 
	echo "praegu on talv"
elif [ $kuu -eq 3 -o $kuu -eq 4 -o $kuu -eq 5 ]; then
	echo "praegu on kevad"
elif [ $kuu -eq 6 -o $kuu -eq 7 -o $kuu -eq 8 ]; then
	echo "praegu on suvi"
elif [ $kuu -eq 9 -o $kuu -eq 10 -o $kuu -eq 11 ];then
	echo "rpaegu on sügis"
else
	echo "antud kuu number ei iksisteeri"
fi
